### PR TITLE
https-ify sass-lang.com urls

### PR DESCRIPTION
**Pull request by asottile**
See https://github.com/sass/sass-site/issues/217

Committed via https://github.com/asottile/all-repos

### CODE REVIEW

**Comment by asottile** [comment]
weird! how did it miss that :S, yeah let me get that too

**Comment by asottile** [comment]
oh! because I included the trailing slash :man_facepalming:

**Comment by am11** [comment]
`git grep sass-lang\.com` 😸

**Comment by asottile** [comment]
yeah my bug was the `sed` command I used: `'s|http://sass-lang.com/|https://sass-lang.com/|g'`

shouldn't have included the slash there :sob:

**Comment by asottile** [comment]
Fortunately it's easy for me to find the ones I missed with the same tooling:

```console
$ all-repos-grep -C all-repos-sass.json http://sass-lang.com | grep -v 'http://sass-lang.com/'
repos-sass/sass/libsass:Readme.md:For more information about Sass itself, please visit http://sass-lang.com
repos-sass/sass/libsass.com:index.html:        <p><a href="http://sass-lang.com">Sass</a> is a pre-processing language for CSS. It allows you to write cleaner stylesheets and makes collaboration on your CSS a breeze. There's a ton of information on Sass out there, so we won't repeat it all here. Just make sure to check out <a href="http://sass-lang.com" target="_blank">the Sass site</a> for tutorials and examples.</p>
repos-sass/sass/node-sass:src/libsass/Readme.md:For more information about Sass itself, please visit http://sass-lang.com
repos-sass/sass/ruby-sass:doc-src/SASS_REFERENCE.md:such as `"Lucida Grande"` or `'http://sass-lang.com'`,
repos-sass/sass/ruby-sass:test/sass/scss/css_test.rb:  f: url(http://sass-lang.com);
repos-sass/sass/sass:doc-src/SASS_REFERENCE.md:such as `"Lucida Grande"` or `'http://sass-lang.com'`,
repos-sass/sass/sass:test/sass/scss/css_test.rb:  f: url(http://sass-lang.com);
repos-sass/sass/sassc:Readme.md:For more information about Sass itself, please visit http://sass-lang.com
```

**Pull request merged**
