### PR TITLE
Windows: Add editorconfig and fix filterpaths for latest libsass

### PR DESCRIPTION
**Pull request by nschonni**
- Add missing LIBSASS_INCLUDES_DIR reference
- Fix AdditionalIncludeDirectories so base.h and the other include\sass
files are found
- Update filter paths from latest libsass.targets

### CODE REVIEW

**Comment by xzyfer** [comment]
Whoa some of that stuff was ancient

**Comment by nschonni** [comment]
Yeah, I'll take a look at setting up Appveyor later, but I thought I'd get it building again separately

**Comment by xzyfer** [comment]
Do you have commit privileges? If so :ship:

**Comment by nschonni** [comment]
Nope, just node-sass, but I usually try to avoid self-merging my stuff. It's shared blame when stuff blows up then :stuck_out_tongue_winking_eye:

**Comment by xzyfer** [comment]
Build stuff is mostly gibberish to me, but I'll peek my head into any PR emails when I have a moment. 
I've invited you to the @sass/sassc so that you're not blocked me :)

**Comment by xzyfer** [comment]
If you're in the area, getting CI setup would be 👌  for lowering risk of self-merging.

**Pull request merged**
