### PR TITLE
Use Travis-CI container-based infrastructure

### PR DESCRIPTION
**Pull request by mgreter**
Update for new travis container based build infrastructure.

### CODE REVIEW

**Comment by am11** [comment]
:+1:

**Comment by am11** [comment]
I have removed d3e1953 from #138 in favour of this. :smile:

**Comment by mgreter** [comment]
Merged the other fixes and will restart Travis-CI to see if it passes ...

**Comment by am11** [comment]
All green! :palm_tree:
I re-pushed https://github.com/sass/sassc/pull/138 too, and all passed there as well.

**Pull request merged**
