### PR TITLE
Update Readme.md with author links.

### PR DESCRIPTION
**Pull request by GimliLongBow**
Hello! I just noticed that none of the authors had links to their Github profiles in the Readme and thought I'd get that in there. What do you think? Thanks!

### CODE REVIEW

**Comment by am11** [comment]
Thanks for bringing this issue to our attention. 💡 

Unfortunately, this change does not render the usernames as link as is.

In addition to your change, hyperlinks need to be defined at the end of the readme as follow:

```markdown
[@hcatlin]: https://github.com/hcatlin
[@akhleung]: https://github.com/akhleung
```

See LibSass readme for reference: https://github.com/sass/libsass/raw/be81001/Readme.md.

Or the links can be inlined as follow:

```markdown
Written by Aaron Leung ([@akhleung](https://github.com/akhleung)) and Hampton Catlin ([@hcatlin](https://github.com/hcatlin))
```

**Comment by GimliLongBow** [comment]
@am11 Thank you for your quick and thorough response! I failed to preview before PR and I apologize for that. I've added in the reference style links so that they will actually work. Thanks again!

**Comment by nschonni** [comment]
This will overlap with #186, but that one needs the original author to validate those other changes, so it doesn't nessesarily block this

**Comment by xzyfer** [comment]
Resolved by #186

**Pull request closed without merging**
