### PR TITLE
Add  script/bootstrap for setting up libsass and sass-spec dependecies

### PR DESCRIPTION
**Pull request by nschonni**
Test to see if the dev has set up the environmental variables for these repos, and clone them out of the source tree if they haven't.

### CODE REVIEW

**Comment by xzyfer** [comment]
Assuming you've testing this :+1:

**Comment by nschonni** [comment]
Found an issue on my OSX machine, so hold off for now

**Comment by nschonni** [comment]
OK,  I replaced the `realpath` stuff because OSX doesn't inlude one unless you `brew install coreutils` http://stackoverflow.com/a/30267480/455535

**Comment by xzyfer** [comment]
Seems sane. I defer to you @nschonni

**Pull request merged**
