### PR TITLE
Update for the new 3.3 header layout

### PR DESCRIPTION
**Pull request by mgreter**
https://github.com/sass/libsass/pull/1538

### CODE REVIEW

**Comment by xzyfer** [comment]
LGTM

**Comment by saper** [comment]
Ok, sorry for being the only one b*thing here about this change :)

I think we should apply `sassc` change first and then apply the libsass change.

We should aim at `sassc` supporting both layouts - otherwise it will be hell to bisect or otherwise trace changes between libsass 3.2.5 and 3.3.

It can be achieved in the following relatively easy ways:

1. Keep old headers around until `3.4`.

2. Keep old name of the `sass_context.h` under `sass` - `sass/sass_context.h` and do something with `sass2scss.h` - so we can just use additional `-I` and things work.

3. `#ifdef` new and old layout, which requires `Makefile` support. More work but the most elegant. We can even provide an `autoconf` macro for others to use to find out how to `#include` libsass properly.

I just tried compiling `sassc` with this change applied against #1538 and unfortunately
you only get compiler warnings and it compiles fine. After that it crashes:

**Comment by saper** [comment]
Oh, it got merged...

**Comment by xzyfer** [comment]
Sorry @saper I didn't see your comment.

> otherwise it will be hell to bisect or otherwise trace changes between libsass 3.2.5 and 3.3.

I don't think this is an issue. We tag sassc release to match libsass releases. We can use the sassc@3.2.5 when bisecting changes in libsass < 3.3 (for the most part). As of this change LibSass is in code freeze.

**Comment by xzyfer** [comment]
@mgreter this appears to break autotools builds of sassc

**Comment by saper** [comment]
> Sorry @saper I didn't see your comment.

No problem, I kept it open in my browser and forgot to send it earlier :)

**Comment by saper** [comment]
@xzyfer "[I told you so](https://github.com/sass/sassc/pull/142#issuecomment-138086624)".  https://github.com/sass/libsass/pull/1540 should fix it.

**Comment by saper** [comment]
and you also need #144

**Comment by xzyfer** [comment]
I feel slightly less useless for not being able to figure this out at 1am.

**Comment by saper** [comment]
> I feel slightly less useless for not being able to figure this out at 1am.

It's fixed in master now by pulling this directly into git by @mgreter

**Comment by xzyfer** [comment]
Yep I saw. I hadn't consider there was a libsass component when trying to
fix this myself last night. I think I'll do some git surgery to squash this
header refactor commits.

**Comment by saper** [comment]
> "... I'll do some git surgery to squash this header refactor commits."

... you lost me here ... :)

**Pull request merged**
