### PR TITLE
Use the error_status from libsass

### PR DESCRIPTION
**Pull request by nschonni**
Related to https://github.com/sass/libsass/issues/2162
I'm not entirely sure about this one, so feel free to close @mgreter 
I'm going to do the other PR to change the libsass error_status value.

### CODE REVIEW

**Comment by xzyfer** [comment]
Assuming libsass returns the appropriate error status this seems sane.

**Comment by mgreter** [comment]
The mapping to OS semantics is out of scope for libsass, since it should be system agnostic. The exit code 65 means ERROR_NETWORK_ACCESS_DENIED on windows. This probably needs a preprocessor macro to have different implementations for windows and unix, but I don't know how ruby sass handles this (might be that exit codes get translated from posix to windows automatically by ruby).

**Comment by mgreter** [comment]
Just checked ruby sass seems to also use exit code 65 (which is IMO wrong) on windows.

**Comment by mgreter** [comment]
I guess it should be [13 "The data is invalid"] [1] on windows .... 
[1]: http://www.hiteksoftware.com/knowledge/articles/049.htm

**Comment by xzyfer** [comment]
>Just checked ruby sass seems to also use exit code 65 (which is IMO wrong) on windows.

Given the disconnect between being Ruby Sass "correct" and semantically correct I think we should put this on the back burner.

I makes sense to get to Ruby Sass semantically correct.

> The mapping to OS semantics is out of scope for libsass, since it should be system agnostic

We may need to implement agnostic error codes in LibSass rather than always return a `1` status code on error.

**Comment by mgreter** [comment]
IMO it does not add enough value to use different error codes as nearly no tools actually use the error code for anything else then showing the appropriate generic error message sometimes. Libsass already returns a specific error message beside indicating that there was "an" error (we actually [have different error codes] [1], but they are not usefull outside of libsass). On another side it is impossible to guess which error code from libsass should map to what system code on a specific OS.

I would keep it as it is and leave the OS specific stuff to the implementors. It makes sense to use something sensible there though and 65/13 seems appropriate enough for nix/win.

[1]: https://github.com/sass/libsass/blob/master/docs/api-doc.md#error-codes

**Comment by xzyfer** [comment]
Given that dart sass will be the future reference implementation I don't believe this makes sense any more.

**Pull request closed without merging**
